const nav=document.getElementById('nav'),menu=document.getElementById('menu'),bg=document.getElementById('burger');
const on=()=>nav.classList.toggle('on',scrollY>40);on();addEventListener('scroll',on,{passive:true});
bg.onclick=()=>{const o=menu.classList.toggle('open');nav.classList.toggle('menu-open',o);bg.setAttribute('aria-expanded',o)};
menu.querySelectorAll('a').forEach(a=>a.onclick=()=>{menu.classList.remove('open');nav.classList.remove('menu-open')});
document.getElementById('rf').onsubmit=e=>{e.preventDefault();const g=id=>document.getElementById(id).value;
const t=`Bonjour, je souhaite réserver une table.\nNom : ${g('n')}\nQuand : ${g('d')}\nPersonnes : ${g('p')}\nTél : ${g('t')}${g('m')?'\nPrécision : '+g('m'):''}`;
window.open('https://wa.me/213667600560?text='+encodeURIComponent(t),'_blank')};
const P=[
{id:'vd',c:'La cave',n:'Vinaigre de dattes',i:'vinaigres',g:'Le doux du fruit, la vivacité de l\'acide.',s:'Le Parrain, 100 % naturel',d:'Un vinaigre artisanal issu de la datte, à la note douce et légèrement caramélisée. Il relève une salade, déglace une poêlée ou finit un plat mijoté.',p:['100 % naturel','Fabrication artisanale','Saveur douce, peu agressive'],f:[['Marque','Le Parrain'],['Format','Bouteille en verre'],['Composition','Datte, sans additifs'],['Conservation','À l\'abri de la lumière, après ouverture au frais']],a:'Salades de crudités, viandes grillées, marinades, plateaux de charcuterie.'},
{id:'vp',c:'La cave',n:'Vinaigre de pomme',i:'vinaigres',g:'Frais, net, fruité.',s:'Le Parrain, 100 % naturel',d:'Un vinaigre de cidre artisanal, franc et rond. Il assaisonne les vinaigrettes du quotidien et réveille les légumes rôtis.',p:['100 % naturel','Fabrication artisanale','Acidité franche et fruitée'],f:[['Marque','Le Parrain'],['Format','Bouteille en verre'],['Composition','Pomme, sans additifs'],['Conservation','À l\'abri de la lumière, après ouverture au frais']],a:'Vinaigrettes, légumes rôtis, poissons, chutneys maison.'},
{id:'hu',c:'La cave',n:'Huile d\'olive',i:'huile-terrine',g:'Le fruité d\'un producteur local.',s:'Producteur local, première pression',d:'Une huile d\'olive de producteur, présentée en bouteille sur les étagères du salon. À employer crue pour garder tout son fruité.',p:['Producteur local','Idéale à cru','Bouteille en verre teintée'],f:[['Origine','Producteur algérien'],['Format','Bouteille 1 L'],['Usage','À cru, en assaisonnement et en finition'],['Conservation','À l\'abri de la chaleur et de la lumière']],a:'Pain grillé, salades, poissons, légumes vapeur, pâtes.'},
{id:'cf',c:'Fait maison',n:'Confiture de fraises',i:'confiture',g:'La fraise dans toute sa pureté.',s:'Recette maison',d:'Une confiture de fraises maison, en pot étiqueté avec son QR code de traçabilité. Peu sucrée, elle garde le goût du fruit.',p:['Fait maison','Étiquette avec QR code','Fruit bien présent'],f:[['Fabrication','Maison, par l\'Épicerie'],['Format','Pot en verre'],['Composition','Fraises, sucre'],['Conservation','Au frais après ouverture']],a:'Tartines, crêpes et galettes sucrées, yaourt, fromage frais.'},
{id:'te',c:'Charcuteries',n:'Terrine en croûte',i:'terrine',g:'Une croûte dorée, un cœur tendre.',s:'Préparée par l\'Épicerie',d:'Une terrine sous croûte, tranchée à la demande et servie avec ses crudités. À partager sur un plateau ou à emporter.',p:['Tranchée à la demande','Servie avec crudités','À partager ou à emporter'],f:[['Fabrication','Maison'],['Service','À la tranche ou entière'],['Conservation','Au frais, à consommer rapidement'],['Accompagnement','Crudités, cornichons']],a:'Plateau de charcuteries, pain complet, vinaigre de dattes, moutarde.'},
{id:'pa',c:'Boulangerie',n:'Pain du jour',i:'pain',g:'Croûte dorée, mie aux flocons.',s:'Série « Les pains »',d:'Chaque jour son pain : un pain complet parsemé de flocons, présenté dans son panier tressé. La variété change avec la fournée.',p:['Fournée du jour','Complet aux flocons','Présenté en panier tressé'],f:[['Fabrication','Sur place'],['Variété','Change selon les jours'],['Conservation','Dans un linge, 2 jours'],['Format','Pain individuel ou à partager']],a:'Petit-déjeuner, terrine, huile d\'olive, confiture de fraises.'}];
const rail=document.getElementById('rail'),dlg=document.getElementById('sheet');
const eye='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" aria-hidden="true"><path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z"/><circle cx="12" cy="12" r="3"/></svg>';
rail.innerHTML=P.map(x=>`<button class="card" data-id="${x.id}" aria-label="Voir la fiche : ${x.n}"><div class="ph"><img src="/assets/img/${x.i}.jpg" alt="" loading="lazy"><span class="pill">${eye}Voir la fiche</span></div><h3>${x.n}</h3><p>${x.g}</p></button>`).join('');
const $=id=>document.getElementById(id);
rail.onclick=e=>{const b=e.target.closest('.card');if(!b)return;const x=P.find(y=>y.id===b.dataset.id);
$('sh-i').src='/assets/img/'+x.i+'.jpg';$('sh-i').alt=x.n;$('sh-c').textContent=x.c;$('sh-t').textContent=x.n;$('sh-g').textContent=x.g;$('sh-d').textContent=x.d;
$('sh-p').innerHTML=x.p.map(t=>`<li>${t}</li>`).join('');$('sh-s').innerHTML=x.f.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');$('sh-a').textContent=x.a;
$('sh-w').href='https://wa.me/213667600560?text='+encodeURIComponent('Bonjour, je souhaite des informations sur : '+x.n);
dlg.showModal();dlg.querySelector('.sh').scrollTop=0;document.body.style.overflow='hidden'};
$('sh-x').onclick=()=>dlg.close();
dlg.addEventListener('close',()=>document.body.style.overflow='');
dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
